model_name = "esrgan" # 模型名称

[srgan]
result_path = "./result"                                             # 结果保存路径
train_resource_path = "/run/media/zyk/Data/数据集/DIV2K/DIV2K_train_HR" # 训练图片资源路径
test_resource_path = "/run/media/zyk/Data/数据集/DIV2K/DIV2K_valid_HR"  # 测试图片资源路径
epochs = 2000                                                        # 训练总轮数
init_epoch = 1                                                       # 初始训练轮数
batch_size = 4                                                       # 单次训练样本数
scale_factor = 4                                                     # 下采样倍数
train_hr_img_height = 128                                            # 训练过程中原图高度
train_hr_img_width = 128                                             # 训练过程中原图宽度
valid_hr_img_height = 384                                            # 验证过程中原图高度
valid_hr_img_width = 384                                             # 验证过程中原图宽度
rdb_num = 16                                                         # 残差块数目
max_workers = 2                                                      # 处理图片的最大线程数
data_enhancement_factor = 1                                          # 数据增强因子
log_interval = 20                                                    # 打印日志间隔
save_images_interval = 1                                             # 保存图片间隔
save_models_interval = 1                                             # 保存模型间隔
save_history_interval = 1                                            # 保存历史数据（损失，准确率）间隔

[esrgan]
result_path = "./result"                                             # 结果保存路径
train_resource_path = "/run/media/zyk/Data/数据集/DIV2K/DIV2K_train_HR" # 训练图片资源路径
test_resource_path = "/run/media/zyk/Data/数据集/DIV2K/DIV2K_valid_HR"  # 测试图片资源路径
# train_resource_path = "/home/hh/zyk/datasets/DF_2K/train_HR" # 训练图片资源路径
# test_resource_path = "/home/hh/zyk/datasets/DF_2K/valid_HR"  # 测试图片资源路径
epochs = 5000               # 训练总轮数
init_epoch = 1              # 初始训练轮数
batch_size = 4              # 单次训练样本数
scale_factor = 4            # 下采样倍数
train_hr_img_height = 128   # 训练过程中原图高度
train_hr_img_width = 128    # 训练过程中原图宽度
valid_hr_img_height = 256   # 验证过程中原图高度
valid_hr_img_width = 256    # 验证过程中原图宽度
max_workers = 4             # 处理图片的最大线程数
data_enhancement_factor = 1 # 数据增强因子
log_interval = 20           # 打印日志间隔
save_images_interval = 5    # 保存图片间隔
save_models_interval = 5    # 保存模型间隔
save_history_interval = 5   # 保存历史数据（损失，准确率）间隔
pretrain_model_path = ""    # 预训练模型路径
use_sn = false              # 是否使用谱归一化层

[real-esrgan]

[adm-esrgan]
